/* 静态页长文案（16 种语言）。
 * i18n.js 放的是生成器界面的短词，这里放「关于与反馈」这类整段正文，
 * 两边分开是为了不把 UI 语言包撑成一个什么都装的大袋子。
 * 带内联标签的键用 data-i18n-html 注入；文案全部由本仓库维护。
 * 法律类页面（隐私政策 / 使用条款 / 数据来源）暂未翻译，仍为中文原文。 */
(function (root) {
  'use strict';
  const C = {};

  C['zh-CN'] = {
    pgBack: '← 返回生成器',
    aboutTitleTag: '关于与反馈 - 小产品实验室',
    aboutLabH: '小产品实验室',
    aboutLabP: '小产品实验室（TinyProductLab）专注于做小而实用的开发者工具。全球地址与人物资料生成器帮助开发者、测试与设计师快速获得符合各国格式习惯的地址与人物资料：打开即生成，选择即更新，全部字段直出，不需要注册账号。',
    aboutCanH: '能做什么',
    aboutCan1: '覆盖 ISO 3166-1 全部 249 个国家 / 地区，22 个国家 / 地区为完整本地化；',
    aboutCan2: '一次给出人物、地址与联系方式、银行卡、工作、账号与技术资料，外加区域地图；',
    aboutCan3: '逐字段复制、复制全部、保存、本地历史、批量生成与 CSV/JSON/JSONL/TXT 导出；',
    aboutCan4: '支持 Seed 复现：同一 Seed + 同一国家 / 城市筛选会得到同一份资料，便于 QA 回归；',
    aboutCan5: '界面支持 16 种语言；本地地址与姓名始终按所选国家的本地语言输出。',
    aboutDataH: '数据边界',
    aboutDataP: '国家、行政区与城市为公开地名数据；姓名、街道、门牌、电话、邮箱、公司、账号等为随机合成数据，<b>不代表真实个人</b>。',
    aboutDataEmail: '<b>邮箱</b>：使用主流服务商域名形式，本地部分随机；不做存在性验证、不发信。',
    aboutDataCard: '<b>银行卡</b>：只按卡组织公开编号结构生成外观数据，不接入真实 BIN 数据库，且所有卡号刻意无法通过 Luhn 校验，不能用于任何真实交易。',
    aboutDataHome: '<b>个人主页</b>：固定落在本站 <code>/u/</code> 路径，避免误指向真实第三方网站（<a href="u/">说明</a>）。',
    aboutDataNo: '<b>不生成</b>身份证号、护照号、社保号 / SSN、税号、银行账户、IBAN、routing number 或生物识别信息。',
    aboutDataMore: '详细说明见<a href="privacy.html">隐私政策</a>、<a href="terms.html">使用条款</a>与<a href="sources.html">数据来源</a>。',
    aboutBugH: 'Bug 反馈建议格式',
    aboutBug1: '国家 / 城市：例如 日本 · 東京都',
    aboutBug2: '错误字段：例如 邮编格式',
    aboutBug3: '期望格式：例如 〒XXX-XXXX',
    aboutBug4: '界面语言与 Seed（如有）：便于我们复现同一份结果',
    aboutBug5: '截图（请勿提交真实身份证、银行卡等敏感资料）',
    qrAlt: '微信公众号二维码：小产品实验室'
  };

  C['zh-TW'] = {
    pgBack: '← 返回產生器',
    aboutTitleTag: '關於與意見回饋 - 小產品實驗室',
    aboutLabH: '小產品實驗室',
    aboutLabP: '小產品實驗室（TinyProductLab）專注於做小而實用的開發者工具。全球地址與人物資料產生器幫助開發者、測試與設計師快速取得符合各國格式習慣的地址與人物資料：打開即產生，選擇即更新，全部欄位直出，不需要註冊帳號。',
    aboutCanH: '能做什麼',
    aboutCan1: '涵蓋 ISO 3166-1 全部 249 個國家 / 地區，22 個國家 / 地區為完整本地化；',
    aboutCan2: '一次給出人物、地址與聯絡方式、金融卡、工作、帳號與技術資料，外加區域地圖；',
    aboutCan3: '逐欄位複製、複製全部、儲存、本機歷史、批次產生與 CSV/JSON/JSONL/TXT 匯出；',
    aboutCan4: '支援 Seed 重現：同一 Seed + 同一國家 / 城市篩選會得到同一份資料，便於 QA 回歸；',
    aboutCan5: '介面支援 16 種語言；本地地址與姓名一律依所選國家的當地語言輸出。',
    aboutDataH: '資料邊界',
    aboutDataP: '國家、行政區與城市為公開地名資料；姓名、街道、門牌、電話、電子郵件、公司、帳號等為隨機合成資料，<b>不代表真實個人</b>。',
    aboutDataEmail: '<b>電子郵件</b>：使用主流服務商網域形式，本地部分隨機；不做存在性驗證、不寄信。',
    aboutDataCard: '<b>金融卡</b>：只依卡片組織公開編號結構產生外觀資料，不接入真實 BIN 資料庫，且所有卡號刻意無法通過 Luhn 檢查，不能用於任何真實交易。',
    aboutDataHome: '<b>個人主頁</b>：固定落在本站 <code>/u/</code> 路徑，避免誤指向真實第三方網站（<a href="u/">說明</a>）。',
    aboutDataNo: '<b>不產生</b>身分證號、護照號、社會安全號 / SSN、稅號、銀行帳戶、IBAN、routing number 或生物辨識資訊。',
    aboutDataMore: '詳細說明請見<a href="privacy.html">隱私政策</a>、<a href="terms.html">使用條款</a>與<a href="sources.html">資料來源</a>。',
    aboutBugH: 'Bug 回報建議格式',
    aboutBug1: '國家 / 城市：例如 日本 · 東京都',
    aboutBug2: '錯誤欄位：例如 郵遞區號格式',
    aboutBug3: '期望格式：例如 〒XXX-XXXX',
    aboutBug4: '介面語言與 Seed（如有）：便於我們重現同一份結果',
    aboutBug5: '螢幕截圖（請勿提交真實身分證、金融卡等敏感資料）',
    qrAlt: '微信公眾號 QR Code：小產品實驗室'
  };

  C.en = {
    pgBack: '← Back to the generator',
    aboutTitleTag: 'About & feedback - TinyProductLab',
    aboutLabH: 'TinyProductLab',
    aboutLabP: 'TinyProductLab builds small, practical developer tools. The global address and profile generator helps developers, testers and designers get addresses and profiles that match each country’s formatting conventions: it generates on open, updates on selection, outputs every field directly, and needs no account.',
    aboutCanH: 'What it does',
    aboutCan1: 'Covers all 249 countries / regions in ISO 3166-1, with 22 fully localised;',
    aboutCan2: 'Gives you person, address and contact details, payment card, work, account and technical data in one go, plus an area map;',
    aboutCan3: 'Per-field copy, copy all, save, local history, batch generation and CSV/JSON/JSONL/TXT export;',
    aboutCan4: 'Reproducible seeds: the same seed plus the same country / city filter always yields the same record, which suits QA regression;',
    aboutCan5: 'The interface supports 16 languages; local addresses and names are always output in the language of the country you pick.',
    aboutDataH: 'Data boundaries',
    aboutDataP: 'Countries, administrative divisions and cities come from public place-name data. Names, streets, house numbers, phone numbers, emails, companies and accounts are randomly synthesised and <b>do not represent real people</b>.',
    aboutDataEmail: '<b>Email</b>: uses the domain shapes of mainstream providers with a random local part; existence is never verified and no mail is sent.',
    aboutDataCard: '<b>Payment card</b>: only the surface structure published by card networks is reproduced. No real BIN database is used, and every number deliberately fails the Luhn check, so none can be used in a real transaction.',
    aboutDataHome: '<b>Personal homepage</b>: always points at this site’s <code>/u/</code> path so it can never mislead anyone to a real third-party site (<a href="u/">details</a>).',
    aboutDataNo: '<b>Never generated</b>: national ID numbers, passport numbers, SSNs, tax IDs, bank accounts, IBANs, routing numbers or biometric data.',
    aboutDataMore: 'For details see the <a href="privacy.html">privacy policy</a>, <a href="terms.html">terms of use</a> and <a href="sources.html">data sources</a>.',
    aboutBugH: 'Suggested bug-report format',
    aboutBug1: 'Country / city — e.g. Japan · Tokyo',
    aboutBug2: 'The wrong field — e.g. postal code format',
    aboutBug3: 'The expected format — e.g. 〒XXX-XXXX',
    aboutBug4: 'Interface language and seed, if any — so we can reproduce the same record',
    aboutBug5: 'A screenshot (please do not send real IDs, payment cards or other sensitive material)',
    qrAlt: 'WeChat official account QR code: TinyProductLab'
  };

  C.ja = {
    pgBack: '← ジェネレーターに戻る',
    aboutTitleTag: 'について・フィードバック - TinyProductLab',
    aboutLabH: 'TinyProductLab（小産品実験室）',
    aboutLabP: 'TinyProductLab は小さく実用的な開発者向けツールを作っています。グローバル住所・人物プロフィールジェネレーターは、開発者・テスター・デザイナーが各国の書式慣習に沿った住所と人物データをすばやく得られるようにするものです。開けばすぐ生成、選べば即更新、全項目をそのまま出力し、アカウント登録は不要です。',
    aboutCanH: 'できること',
    aboutCan1: 'ISO 3166-1 の 249 の国 / 地域すべてに対応し、うち 22 か国 / 地域は完全ローカライズ済み。',
    aboutCan2: '人物・住所と連絡先・カード・勤務先・アカウントと技術情報を一度に生成し、地域地図も表示。',
    aboutCan3: '項目ごとのコピー、全項目コピー、保存、ローカル履歴、一括生成と CSV/JSON/JSONL/TXT 書き出し。',
    aboutCan4: 'シード再現に対応：同じシードと同じ国 / 都市の絞り込みなら常に同じデータになるため、QA の回帰確認に使えます。',
    aboutCan5: 'UI は 16 言語対応。現地表記の住所と氏名は常に選んだ国の言語で出力されます。',
    aboutDataH: 'データの範囲',
    aboutDataP: '国・行政区分・都市は公開の地名データです。氏名、通り名、番地、電話番号、メール、会社、アカウントなどはランダムに合成したもので、<b>実在の個人を表すものではありません</b>。',
    aboutDataEmail: '<b>メール</b>：主要プロバイダーのドメイン形式を使い、ローカル部分はランダムです。存在確認はせず、送信も行いません。',
    aboutDataCard: '<b>カード</b>：カードブランドが公開している番号構造の見た目だけを再現しています。実際の BIN データベースは使っておらず、すべての番号は意図的に Luhn チェックを通らないため、実際の決済には使えません。',
    aboutDataHome: '<b>個人ホームページ</b>：必ず当サイトの <code>/u/</code> パスを指すため、実在の第三者サイトへ誤って誘導することはありません（<a href="u/">説明</a>）。',
    aboutDataNo: '<b>生成しないもの</b>：マイナンバーなどの身分証番号、パスポート番号、社会保障番号 / SSN、納税者番号、銀行口座、IBAN、routing number、生体情報。',
    aboutDataMore: '詳しくは<a href="privacy.html">プライバシーポリシー</a>、<a href="terms.html">利用規約</a>、<a href="sources.html">データ出典</a>をご覧ください。',
    aboutBugH: '不具合報告のおすすめ書式',
    aboutBug1: '国 / 都市：例）日本 · 東京都',
    aboutBug2: '誤っている項目：例）郵便番号の書式',
    aboutBug3: '期待する書式：例）〒XXX-XXXX',
    aboutBug4: 'UI 言語とシード（あれば）：同じ結果を再現するために必要です',
    aboutBug5: 'スクリーンショット（実物の身分証やカードなど、機密情報は送らないでください）',
    qrAlt: 'WeChat 公式アカウントの QR コード：TinyProductLab'
  };

  C.ko = {
    pgBack: '← 생성기로 돌아가기',
    aboutTitleTag: '소개 및 피드백 - TinyProductLab',
    aboutLabH: 'TinyProductLab',
    aboutLabP: 'TinyProductLab은 작고 실용적인 개발자 도구를 만듭니다. 글로벌 주소·인물 프로필 생성기는 개발자, 테스터, 디자이너가 각 나라의 서식 관행에 맞는 주소와 인물 데이터를 빠르게 얻도록 돕습니다. 열면 바로 생성되고, 선택하면 즉시 갱신되며, 모든 항목을 그대로 출력하고 계정 등록이 필요 없습니다.',
    aboutCanH: '무엇을 할 수 있나요',
    aboutCan1: 'ISO 3166-1의 249개 국가 / 지역 전체를 포함하며 그중 22개는 완전히 현지화되어 있습니다.',
    aboutCan2: '인물, 주소와 연락처, 결제 카드, 직장, 계정과 기술 정보를 한 번에 생성하고 지역 지도도 함께 보여줍니다.',
    aboutCan3: '항목별 복사, 전체 복사, 저장, 로컬 기록, 일괄 생성과 CSV/JSON/JSONL/TXT 내보내기.',
    aboutCan4: '시드 재현 지원: 같은 시드와 같은 국가 / 도시 필터라면 항상 같은 데이터가 나오므로 QA 회귀 테스트에 적합합니다.',
    aboutCan5: '인터페이스는 16개 언어를 지원하며, 현지 주소와 이름은 항상 선택한 나라의 언어로 출력됩니다.',
    aboutDataH: '데이터 경계',
    aboutDataP: '국가, 행정구역, 도시는 공개된 지명 데이터입니다. 이름, 도로명, 번지, 전화번호, 이메일, 회사, 계정 등은 무작위로 합성한 것이며 <b>실제 개인을 나타내지 않습니다</b>.',
    aboutDataEmail: '<b>이메일</b>: 주요 제공업체의 도메인 형태를 쓰고 로컬 부분은 무작위입니다. 존재 여부를 확인하지 않고 메일도 보내지 않습니다.',
    aboutDataCard: '<b>결제 카드</b>: 카드사가 공개한 번호 구조의 겉모습만 재현합니다. 실제 BIN 데이터베이스를 쓰지 않으며, 모든 번호는 의도적으로 Luhn 검증을 통과하지 못하므로 실제 결제에 쓸 수 없습니다.',
    aboutDataHome: '<b>개인 홈페이지</b>: 항상 이 사이트의 <code>/u/</code> 경로를 가리켜 실제 제3자 사이트로 잘못 안내하지 않습니다(<a href="u/">설명</a>).',
    aboutDataNo: '<b>생성하지 않는 항목</b>: 주민등록번호 등 신분증 번호, 여권 번호, 사회보장번호 / SSN, 납세자 번호, 은행 계좌, IBAN, routing number, 생체 정보.',
    aboutDataMore: '자세한 내용은 <a href="privacy.html">개인정보 처리방침</a>, <a href="terms.html">이용약관</a>, <a href="sources.html">데이터 출처</a>를 참고하세요.',
    aboutBugH: '버그 신고 권장 형식',
    aboutBug1: '국가 / 도시: 예) 일본 · 도쿄도',
    aboutBug2: '잘못된 항목: 예) 우편번호 형식',
    aboutBug3: '기대하는 형식: 예) 〒XXX-XXXX',
    aboutBug4: '인터페이스 언어와 시드(있다면): 같은 결과를 재현하는 데 필요합니다',
    aboutBug5: '스크린샷(실제 신분증이나 카드 등 민감한 자료는 보내지 마세요)',
    qrAlt: 'WeChat 공식 계정 QR 코드: TinyProductLab'
  };

  C.de = {
    pgBack: '← Zurück zum Generator',
    aboutTitleTag: 'Über uns & Feedback - TinyProductLab',
    aboutLabH: 'TinyProductLab',
    aboutLabP: 'TinyProductLab baut kleine, praktische Entwickler-Tools. Der globale Adress- und Profilgenerator hilft Entwicklern, Testern und Designern, schnell Adressen und Personendaten zu erhalten, die den Formatkonventionen des jeweiligen Landes entsprechen: Er generiert beim Öffnen, aktualisiert bei jeder Auswahl, gibt alle Felder direkt aus und braucht kein Konto.',
    aboutCanH: 'Was es kann',
    aboutCan1: 'Deckt alle 249 Länder / Regionen nach ISO 3166-1 ab, davon 22 vollständig lokalisiert;',
    aboutCan2: 'Liefert Person, Adresse und Kontaktdaten, Zahlungskarte, Beruf, Konto- und technische Daten in einem Durchgang, dazu eine Gebietskarte;',
    aboutCan3: 'Feldweise kopieren, alles kopieren, speichern, lokaler Verlauf, Stapelerzeugung und Export als CSV/JSON/JSONL/TXT;',
    aboutCan4: 'Reproduzierbare Seeds: derselbe Seed mit demselben Land-/Stadtfilter ergibt immer denselben Datensatz — praktisch für QA-Regressionen;',
    aboutCan5: 'Die Oberfläche gibt es in 16 Sprachen; lokale Adressen und Namen erscheinen stets in der Sprache des gewählten Landes.',
    aboutDataH: 'Datengrenzen',
    aboutDataP: 'Länder, Verwaltungseinheiten und Städte stammen aus öffentlichen Ortsnamendaten. Namen, Straßen, Hausnummern, Telefonnummern, E-Mail-Adressen, Firmen und Konten sind zufällig synthetisiert und <b>stehen für keine realen Personen</b>.',
    aboutDataEmail: '<b>E-Mail</b>: nutzt die Domainformen verbreiteter Anbieter, der lokale Teil ist zufällig. Es wird keine Existenz geprüft und keine Mail versendet.',
    aboutDataCard: '<b>Zahlungskarte</b>: nachgebildet wird nur die von den Kartennetzwerken veröffentlichte Nummernstruktur. Es kommt keine echte BIN-Datenbank zum Einsatz, und jede Nummer scheitert absichtlich an der Luhn-Prüfung, ist also für echte Transaktionen unbrauchbar.',
    aboutDataHome: '<b>Persönliche Homepage</b>: zeigt immer auf den Pfad <code>/u/</code> dieser Seite und kann daher nie auf eine echte fremde Website verweisen (<a href="u/">Erläuterung</a>).',
    aboutDataNo: '<b>Nicht erzeugt werden</b>: Ausweisnummern, Passnummern, Sozialversicherungsnummern / SSN, Steuernummern, Bankkonten, IBANs, Routing Numbers oder biometrische Daten.',
    aboutDataMore: 'Näheres in der <a href="privacy.html">Datenschutzerklärung</a>, den <a href="terms.html">Nutzungsbedingungen</a> und den <a href="sources.html">Datenquellen</a>.',
    aboutBugH: 'Empfohlenes Format für Fehlermeldungen',
    aboutBug1: 'Land / Stadt — z. B. Japan · Tokio',
    aboutBug2: 'Das falsche Feld — z. B. Format der Postleitzahl',
    aboutBug3: 'Das erwartete Format — z. B. 〒XXX-XXXX',
    aboutBug4: 'Oberflächensprache und Seed, falls vorhanden — damit wir denselben Datensatz reproduzieren können',
    aboutBug5: 'Ein Screenshot (bitte keine echten Ausweise, Karten oder andere sensiblen Unterlagen senden)',
    qrAlt: 'QR-Code des WeChat-Kanals: TinyProductLab'
  };

  C.fr = {
    pgBack: '← Retour au générateur',
    aboutTitleTag: 'À propos et retours - TinyProductLab',
    aboutLabH: 'TinyProductLab',
    aboutLabP: 'TinyProductLab conçoit de petits outils utiles pour les développeurs. Le générateur mondial d’adresses et de profils permet aux développeurs, testeurs et designers d’obtenir rapidement des adresses et des profils conformes aux conventions de mise en forme de chaque pays : il génère à l’ouverture, se met à jour à chaque sélection, restitue tous les champs directement et ne demande aucun compte.',
    aboutCanH: 'Ce qu’il fait',
    aboutCan1: 'Couvre les 249 pays / territoires de la norme ISO 3166-1, dont 22 entièrement localisés ;',
    aboutCan2: 'Fournit en une fois la personne, l’adresse et les coordonnées, la carte de paiement, l’emploi, les données de compte et techniques, plus une carte de la zone ;',
    aboutCan3: 'Copie champ par champ, copie globale, enregistrement, historique local, génération par lots et export CSV/JSON/JSONL/TXT ;',
    aboutCan4: 'Graines reproductibles : la même graine avec le même filtre pays / ville redonne toujours le même enregistrement, ce qui convient aux tests de régression ;',
    aboutCan5: 'L’interface existe en 16 langues ; les adresses et noms locaux sortent toujours dans la langue du pays choisi.',
    aboutDataH: 'Limites des données',
    aboutDataP: 'Les pays, divisions administratives et villes proviennent de données toponymiques publiques. Les noms, rues, numéros, téléphones, e-mails, sociétés et comptes sont synthétisés au hasard et <b>ne correspondent à aucune personne réelle</b>.',
    aboutDataEmail: '<b>E-mail</b> : reprend la forme des domaines des principaux fournisseurs, avec une partie locale aléatoire ; aucune existence n’est vérifiée et aucun message n’est envoyé.',
    aboutDataCard: '<b>Carte de paiement</b> : seule la structure de numérotation publiée par les réseaux est reproduite. Aucune base BIN réelle n’est utilisée et chaque numéro échoue volontairement au contrôle de Luhn : aucun ne peut servir à une vraie transaction.',
    aboutDataHome: '<b>Page personnelle</b> : pointe toujours vers le chemin <code>/u/</code> de ce site, afin de ne jamais renvoyer par erreur vers un site tiers réel (<a href="u/">explication</a>).',
    aboutDataNo: '<b>Jamais générés</b> : numéros de pièce d’identité, de passeport, de sécurité sociale / SSN, identifiants fiscaux, comptes bancaires, IBAN, routing numbers ou données biométriques.',
    aboutDataMore: 'Pour le détail, voir la <a href="privacy.html">politique de confidentialité</a>, les <a href="terms.html">conditions d’utilisation</a> et les <a href="sources.html">sources de données</a>.',
    aboutBugH: 'Format conseillé pour signaler un bug',
    aboutBug1: 'Pays / ville — par exemple Japon · Tokyo',
    aboutBug2: 'Le champ erroné — par exemple le format du code postal',
    aboutBug3: 'Le format attendu — par exemple 〒XXX-XXXX',
    aboutBug4: 'La langue de l’interface et la graine, le cas échéant — pour que nous puissions reproduire le même enregistrement',
    aboutBug5: 'Une capture d’écran (merci de ne pas envoyer de pièces d’identité, cartes bancaires ou autres éléments sensibles réels)',
    qrAlt: 'QR code du compte officiel WeChat : TinyProductLab'
  };

  C.es = {
    pgBack: '← Volver al generador',
    aboutTitleTag: 'Acerca de y comentarios - TinyProductLab',
    aboutLabH: 'TinyProductLab',
    aboutLabP: 'TinyProductLab crea herramientas pequeñas y prácticas para desarrolladores. El generador global de direcciones y perfiles ayuda a desarrolladores, testers y diseñadores a obtener rápidamente direcciones y perfiles que siguen las convenciones de formato de cada país: genera al abrir, se actualiza al seleccionar, entrega todos los campos directamente y no requiere cuenta.',
    aboutCanH: 'Qué hace',
    aboutCan1: 'Cubre los 249 países / regiones de la norma ISO 3166-1, de los cuales 22 están completamente localizados;',
    aboutCan2: 'Entrega de una vez persona, dirección y datos de contacto, tarjeta de pago, empleo, cuenta y datos técnicos, más un mapa de la zona;',
    aboutCan3: 'Copia por campo, copiar todo, guardar, historial local, generación por lotes y exportación a CSV/JSON/JSONL/TXT;',
    aboutCan4: 'Semillas reproducibles: la misma semilla con el mismo filtro de país / ciudad devuelve siempre el mismo registro, útil para pruebas de regresión;',
    aboutCan5: 'La interfaz está en 16 idiomas; las direcciones y nombres locales salen siempre en el idioma del país elegido.',
    aboutDataH: 'Límites de los datos',
    aboutDataP: 'Los países, divisiones administrativas y ciudades provienen de datos toponímicos públicos. Los nombres, calles, números, teléfonos, correos, empresas y cuentas se sintetizan al azar y <b>no corresponden a personas reales</b>.',
    aboutDataEmail: '<b>Correo</b>: usa la forma de dominio de los proveedores habituales con una parte local aleatoria; no se comprueba su existencia ni se envía ningún mensaje.',
    aboutDataCard: '<b>Tarjeta de pago</b>: solo se reproduce la estructura de numeración publicada por las redes de tarjetas. No se usa ninguna base BIN real y todos los números fallan a propósito la comprobación de Luhn, así que ninguno sirve para una transacción real.',
    aboutDataHome: '<b>Página personal</b>: siempre apunta a la ruta <code>/u/</code> de este sitio, para no dirigir por error a un sitio de terceros real (<a href="u/">explicación</a>).',
    aboutDataNo: '<b>Nunca se generan</b>: números de documento de identidad, de pasaporte, de seguridad social / SSN, identificadores fiscales, cuentas bancarias, IBAN, routing numbers ni datos biométricos.',
    aboutDataMore: 'Más detalles en la <a href="privacy.html">política de privacidad</a>, las <a href="terms.html">condiciones de uso</a> y las <a href="sources.html">fuentes de datos</a>.',
    aboutBugH: 'Formato sugerido para informar de un error',
    aboutBug1: 'País / ciudad — por ejemplo Japón · Tokio',
    aboutBug2: 'El campo incorrecto — por ejemplo el formato del código postal',
    aboutBug3: 'El formato esperado — por ejemplo 〒XXX-XXXX',
    aboutBug4: 'El idioma de la interfaz y la semilla, si la hay — para poder reproducir el mismo registro',
    aboutBug5: 'Una captura de pantalla (por favor, no envíes documentos de identidad, tarjetas ni otro material sensible real)',
    qrAlt: 'Código QR de la cuenta oficial de WeChat: TinyProductLab'
  };

  C.pt = {
    pgBack: '← Voltar ao gerador',
    aboutTitleTag: 'Sobre e feedback - TinyProductLab',
    aboutLabH: 'TinyProductLab',
    aboutLabP: 'A TinyProductLab cria ferramentas pequenas e práticas para quem programa. O gerador global de endereços e perfis ajuda desenvolvedores, testadores e designers a obter rapidamente endereços e perfis que seguem as convenções de formato de cada país: gera ao abrir, atualiza ao selecionar, entrega todos os campos direto e não exige conta.',
    aboutCanH: 'O que faz',
    aboutCan1: 'Cobre os 249 países / regiões da norma ISO 3166-1, com 22 totalmente localizados;',
    aboutCan2: 'Entrega de uma vez pessoa, endereço e contato, cartão de pagamento, trabalho, conta e dados técnicos, além de um mapa da área;',
    aboutCan3: 'Cópia por campo, copiar tudo, salvar, histórico local, geração em lote e exportação em CSV/JSON/JSONL/TXT;',
    aboutCan4: 'Seeds reproduzíveis: a mesma seed com o mesmo filtro de país / cidade devolve sempre o mesmo registro, o que serve para testes de regressão;',
    aboutCan5: 'A interface tem 16 idiomas; endereços e nomes locais saem sempre no idioma do país escolhido.',
    aboutDataH: 'Limites dos dados',
    aboutDataP: 'Países, divisões administrativas e cidades vêm de dados toponímicos públicos. Nomes, ruas, números, telefones, e-mails, empresas e contas são sintetizados aleatoriamente e <b>não representam pessoas reais</b>.',
    aboutDataEmail: '<b>E-mail</b>: usa o formato de domínio dos provedores mais comuns, com a parte local aleatória; a existência nunca é verificada e nenhuma mensagem é enviada.',
    aboutDataCard: '<b>Cartão de pagamento</b>: reproduz apenas a estrutura de numeração publicada pelas bandeiras. Nenhuma base BIN real é usada e todos os números falham de propósito na verificação de Luhn, portanto nenhum serve para uma transação real.',
    aboutDataHome: '<b>Página pessoal</b>: aponta sempre para o caminho <code>/u/</code> deste site, para nunca levar por engano a um site de terceiros real (<a href="u/">explicação</a>).',
    aboutDataNo: '<b>Nunca são gerados</b>: números de documento de identidade, de passaporte, de seguridade social / SSN, identificações fiscais, contas bancárias, IBAN, routing numbers ou dados biométricos.',
    aboutDataMore: 'Mais detalhes na <a href="privacy.html">política de privacidade</a>, nos <a href="terms.html">termos de uso</a> e nas <a href="sources.html">fontes de dados</a>.',
    aboutBugH: 'Formato sugerido para relatar um erro',
    aboutBug1: 'País / cidade — por exemplo Japão · Tóquio',
    aboutBug2: 'O campo errado — por exemplo o formato do código postal',
    aboutBug3: 'O formato esperado — por exemplo 〒XXX-XXXX',
    aboutBug4: 'O idioma da interface e a seed, se houver — para reproduzirmos o mesmo registro',
    aboutBug5: 'Uma captura de tela (por favor, não envie documentos, cartões ou outro material sensível real)',
    qrAlt: 'Código QR da conta oficial no WeChat: TinyProductLab'
  };

  C.it = {
    pgBack: '← Torna al generatore',
    aboutTitleTag: 'Informazioni e feedback - TinyProductLab',
    aboutLabH: 'TinyProductLab',
    aboutLabP: 'TinyProductLab realizza piccoli strumenti utili per chi sviluppa. Il generatore globale di indirizzi e profili aiuta sviluppatori, tester e designer a ottenere in fretta indirizzi e profili conformi alle convenzioni di formato di ciascun paese: genera all’apertura, si aggiorna a ogni selezione, restituisce tutti i campi direttamente e non richiede alcun account.',
    aboutCanH: 'Cosa fa',
    aboutCan1: 'Copre tutti i 249 paesi / territori della norma ISO 3166-1, di cui 22 completamente localizzati;',
    aboutCan2: 'Fornisce in una sola volta persona, indirizzo e contatti, carta di pagamento, lavoro, dati di account e tecnici, più una mappa dell’area;',
    aboutCan3: 'Copia campo per campo, copia tutto, salvataggio, cronologia locale, generazione in blocco ed esportazione CSV/JSON/JSONL/TXT;',
    aboutCan4: 'Seed riproducibili: lo stesso seed con lo stesso filtro paese / città restituisce sempre lo stesso record, utile per i test di regressione;',
    aboutCan5: 'L’interfaccia è disponibile in 16 lingue; indirizzi e nomi locali escono sempre nella lingua del paese scelto.',
    aboutDataH: 'Limiti dei dati',
    aboutDataP: 'Paesi, suddivisioni amministrative e città provengono da dati toponomastici pubblici. Nomi, vie, numeri civici, telefoni, e-mail, aziende e account sono sintetizzati a caso e <b>non rappresentano persone reali</b>.',
    aboutDataEmail: '<b>E-mail</b>: usa la forma dei domini dei provider più diffusi con una parte locale casuale; l’esistenza non viene mai verificata e non viene inviato alcun messaggio.',
    aboutDataCard: '<b>Carta di pagamento</b>: viene riprodotta solo la struttura di numerazione pubblicata dai circuiti. Non si usa alcun database BIN reale e ogni numero non supera volutamente il controllo di Luhn, quindi nessuno è utilizzabile in una transazione reale.',
    aboutDataHome: '<b>Pagina personale</b>: punta sempre al percorso <code>/u/</code> di questo sito, per non rimandare mai per errore a un sito di terzi reale (<a href="u/">spiegazione</a>).',
    aboutDataNo: '<b>Mai generati</b>: numeri di documento d’identità, di passaporto, di previdenza sociale / SSN, codici fiscali, conti bancari, IBAN, routing number o dati biometrici.',
    aboutDataMore: 'Per i dettagli vedi l’<a href="privacy.html">informativa sulla privacy</a>, i <a href="terms.html">termini d’uso</a> e le <a href="sources.html">fonti dei dati</a>.',
    aboutBugH: 'Formato consigliato per segnalare un bug',
    aboutBug1: 'Paese / città — per esempio Giappone · Tokyo',
    aboutBug2: 'Il campo sbagliato — per esempio il formato del codice postale',
    aboutBug3: 'Il formato atteso — per esempio 〒XXX-XXXX',
    aboutBug4: 'La lingua dell’interfaccia e il seed, se presente — così possiamo riprodurre lo stesso record',
    aboutBug5: 'Uno screenshot (per favore non inviare documenti, carte o altro materiale sensibile reale)',
    qrAlt: 'Codice QR dell’account ufficiale WeChat: TinyProductLab'
  };

  C.ru = {
    pgBack: '← Назад к генератору',
    aboutTitleTag: 'О проекте и обратная связь - TinyProductLab',
    aboutLabH: 'TinyProductLab',
    aboutLabP: 'TinyProductLab делает небольшие практичные инструменты для разработчиков. Глобальный генератор адресов и профилей помогает разработчикам, тестировщикам и дизайнерам быстро получать адреса и профили, соответствующие правилам оформления каждой страны: генерирует при открытии, обновляет при выборе, выдаёт все поля сразу и не требует регистрации.',
    aboutCanH: 'Что он умеет',
    aboutCan1: 'Охватывает все 249 стран / территорий по ISO 3166-1, из них 22 полностью локализованы;',
    aboutCan2: 'Сразу выдаёт человека, адрес и контакты, платёжную карту, работу, аккаунт и технические данные, плюс карту района;',
    aboutCan3: 'Копирование по полю, копирование всего, сохранение, локальная история, пакетная генерация и экспорт в CSV/JSON/JSONL/TXT;',
    aboutCan4: 'Воспроизводимые сиды: один и тот же сид с тем же фильтром страны / города всегда даёт одну и ту же запись — удобно для регрессионных проверок;',
    aboutCan5: 'Интерфейс на 16 языках; местные адреса и имена всегда выводятся на языке выбранной страны.',
    aboutDataH: 'Границы данных',
    aboutDataP: 'Страны, административные единицы и города взяты из открытых данных о географических названиях. Имена, улицы, номера домов, телефоны, адреса почты, компании и аккаунты синтезированы случайно и <b>не относятся к реальным людям</b>.',
    aboutDataEmail: '<b>Почта</b>: используется форма доменов распространённых провайдеров со случайной локальной частью; существование не проверяется, письма не отправляются.',
    aboutDataCard: '<b>Платёжная карта</b>: воспроизводится только структура нумерации, опубликованная платёжными системами. Реальная база BIN не используется, и каждый номер намеренно не проходит проверку Луна, поэтому ни один не годится для настоящей операции.',
    aboutDataHome: '<b>Личная страница</b>: всегда указывает на путь <code>/u/</code> этого сайта, чтобы никогда по ошибке не привести на реальный сторонний сайт (<a href="u/">пояснение</a>).',
    aboutDataNo: '<b>Никогда не генерируются</b>: номера удостоверений личности, паспортов, социального страхования / SSN, налоговые номера, банковские счета, IBAN, routing number и биометрические данные.',
    aboutDataMore: 'Подробнее — в <a href="privacy.html">политике конфиденциальности</a>, <a href="terms.html">условиях использования</a> и <a href="sources.html">источниках данных</a>.',
    aboutBugH: 'Рекомендуемый формат сообщения об ошибке',
    aboutBug1: 'Страна / город — например Япония · Токио',
    aboutBug2: 'Неверное поле — например формат почтового индекса',
    aboutBug3: 'Ожидаемый формат — например 〒XXX-XXXX',
    aboutBug4: 'Язык интерфейса и сид, если он был — чтобы мы воспроизвели ту же запись',
    aboutBug5: 'Снимок экрана (пожалуйста, не присылайте реальные документы, карты и другие конфиденциальные материалы)',
    qrAlt: 'QR-код официального аккаунта WeChat: TinyProductLab'
  };

  C.ar = {
    pgBack: '← العودة إلى المُولِّد',
    aboutTitleTag: 'حول المشروع والملاحظات - TinyProductLab',
    aboutLabH: 'TinyProductLab',
    aboutLabP: 'تصنع TinyProductLab أدوات صغيرة وعملية للمطوّرين. يساعد مُولِّد العناوين والملفات الشخصية العالمي المطوّرين والمختبِرين والمصمّمين على الحصول سريعًا على عناوين وبيانات أشخاص تتوافق مع أعراف التنسيق في كل بلد: يُولِّد عند الفتح، ويُحدِّث عند الاختيار، ويُخرج كل الحقول مباشرة، ولا يحتاج إلى حساب.',
    aboutCanH: 'ما يقوم به',
    aboutCan1: 'يشمل جميع الدول / المناطق الـ 249 في معيار ISO 3166-1، منها 22 مُعرَّبة ومحلّية بالكامل؛',
    aboutCan2: 'يقدّم في مرة واحدة الشخص والعنوان وبيانات الاتصال وبطاقة الدفع والعمل وبيانات الحساب والبيانات التقنية، مع خريطة للمنطقة؛',
    aboutCan3: 'نسخ كل حقل على حدة، ونسخ الكل، والحفظ، وسجل محلي، وتوليد بالدفعات، وتصدير CSV/JSON/JSONL/TXT؛',
    aboutCan4: 'بذور قابلة للتكرار: البذرة نفسها مع مُرشِّح البلد / المدينة نفسه تُعطي دائمًا السجل نفسه، وهو ما يناسب اختبارات الانحدار؛',
    aboutCan5: 'الواجهة متاحة بـ 16 لغة؛ أما العناوين والأسماء المحلية فتُخرَج دائمًا بلغة البلد المختار.',
    aboutDataH: 'حدود البيانات',
    aboutDataP: 'الدول والتقسيمات الإدارية والمدن مأخوذة من بيانات أسماء أماكن عامة. أما الأسماء والشوارع وأرقام المنازل والهواتف والبريد والشركات والحسابات فهي مُركَّبة عشوائيًا و<b>لا تمثّل أشخاصًا حقيقيين</b>.',
    aboutDataEmail: '<b>البريد</b>: يستخدم صيغة نطاقات المزوّدين المعروفين مع جزء محلي عشوائي؛ لا يُتحقَّق من وجوده ولا تُرسَل أي رسالة.',
    aboutDataCard: '<b>بطاقة الدفع</b>: يُحاكى فقط هيكل الترقيم الذي تنشره شبكات البطاقات. لا تُستخدم أي قاعدة BIN حقيقية، وكل رقم يفشل عمدًا في اختبار Luhn، فلا يصلح أي منها لعملية دفع حقيقية.',
    aboutDataHome: '<b>الصفحة الشخصية</b>: تشير دائمًا إلى المسار <code>/u/</code> في هذا الموقع، حتى لا تُحيل بالخطأ إلى موقع خارجي حقيقي (<a href="u/">توضيح</a>).',
    aboutDataNo: '<b>لا تُولَّد أبدًا</b>: أرقام الهوية الوطنية وجوازات السفر والضمان الاجتماعي / SSN والأرقام الضريبية والحسابات المصرفية وIBAN وrouting number أو البيانات الحيوية.',
    aboutDataMore: 'للتفاصيل راجع <a href="privacy.html">سياسة الخصوصية</a> و<a href="terms.html">شروط الاستخدام</a> و<a href="sources.html">مصادر البيانات</a>.',
    aboutBugH: 'الصيغة المقترحة للإبلاغ عن خطأ',
    aboutBug1: 'البلد / المدينة — مثال: اليابان · طوكيو',
    aboutBug2: 'الحقل الخاطئ — مثال: صيغة الرمز البريدي',
    aboutBug3: 'الصيغة المتوقّعة — مثال: 〒XXX-XXXX',
    aboutBug4: 'لغة الواجهة والبذرة إن وُجدت — حتى نتمكّن من إعادة إنتاج السجل نفسه',
    aboutBug5: 'صورة للشاشة (من فضلك لا ترسل هويات أو بطاقات حقيقية أو أي مواد حسّاسة)',
    qrAlt: 'رمز QR لحساب ويتشات الرسمي: TinyProductLab'
  };

  C.hi = {
    pgBack: '← जेनरेटर पर वापस',
    aboutTitleTag: 'परिचय और फ़ीडबैक - TinyProductLab',
    aboutLabH: 'TinyProductLab',
    aboutLabP: 'TinyProductLab छोटे और काम के डेवलपर टूल बनाती है। ग्लोबल पता और प्रोफ़ाइल जेनरेटर डेवलपर, टेस्टर और डिज़ाइनर को ऐसे पते और प्रोफ़ाइल तेज़ी से देता है जो हर देश की फ़ॉर्मैट परंपरा से मेल खाते हैं: खोलते ही बन जाता है, चुनते ही बदल जाता है, सभी फ़ील्ड सीधे देता है और किसी खाते की ज़रूरत नहीं।',
    aboutCanH: 'यह क्या करता है',
    aboutCan1: 'ISO 3166-1 के सभी 249 देश / क्षेत्र शामिल हैं, जिनमें 22 पूरी तरह स्थानीयकृत हैं;',
    aboutCan2: 'एक ही बार में व्यक्ति, पता और संपर्क, भुगतान कार्ड, नौकरी, खाता और तकनीकी जानकारी देता है, साथ में इलाक़े का नक़्शा;',
    aboutCan3: 'फ़ील्ड-दर-फ़ील्ड कॉपी, सब कॉपी, सहेजना, स्थानीय इतिहास, बैच जेनरेशन और CSV/JSON/JSONL/TXT एक्सपोर्ट;',
    aboutCan4: 'दोहराने योग्य सीड: वही सीड और वही देश / शहर फ़िल्टर हमेशा वही रिकॉर्ड देता है, जो QA रिग्रेशन के लिए उपयोगी है;',
    aboutCan5: 'इंटरफ़ेस 16 भाषाओं में है; स्थानीय पते और नाम हमेशा चुने हुए देश की भाषा में निकलते हैं।',
    aboutDataH: 'डेटा की सीमाएँ',
    aboutDataP: 'देश, प्रशासनिक इकाइयाँ और शहर सार्वजनिक स्थान-नाम डेटा से आते हैं। नाम, सड़क, मकान नंबर, फ़ोन, ईमेल, कंपनी और खाते बेतरतीब ढंग से बनाए गए हैं और <b>किसी वास्तविक व्यक्ति को नहीं दर्शाते</b>।',
    aboutDataEmail: '<b>ईमेल</b>: प्रचलित सेवाओं के डोमेन रूप का उपयोग होता है और लोकल हिस्सा बेतरतीब होता है; अस्तित्व की जाँच नहीं होती और कोई मेल नहीं भेजा जाता।',
    aboutDataCard: '<b>भुगतान कार्ड</b>: केवल कार्ड नेटवर्क द्वारा प्रकाशित नंबर संरचना की नक़ल की जाती है। कोई वास्तविक BIN डेटाबेस नहीं है, और हर नंबर जान-बूझकर Luhn जाँच में विफल होता है, इसलिए कोई भी असली लेन-देन में काम नहीं आएगा।',
    aboutDataHome: '<b>निजी होमपेज</b>: हमेशा इस साइट के <code>/u/</code> पथ पर जाता है, ताकि किसी असली तीसरे-पक्ष की साइट पर ग़लती से न ले जाए (<a href="u/">विवरण</a>)।',
    aboutDataNo: '<b>कभी नहीं बनाए जाते</b>: पहचान-पत्र संख्या, पासपोर्ट संख्या, सामाजिक सुरक्षा संख्या / SSN, कर पहचान, बैंक खाते, IBAN, routing number या बायोमेट्रिक डेटा।',
    aboutDataMore: 'विस्तार से देखें <a href="privacy.html">गोपनीयता नीति</a>, <a href="terms.html">उपयोग की शर्तें</a> और <a href="sources.html">डेटा स्रोत</a>।',
    aboutBugH: 'बग बताने का सुझाया गया प्रारूप',
    aboutBug1: 'देश / शहर — जैसे जापान · टोक्यो',
    aboutBug2: 'ग़लत फ़ील्ड — जैसे पिन कोड का प्रारूप',
    aboutBug3: 'अपेक्षित प्रारूप — जैसे 〒XXX-XXXX',
    aboutBug4: 'इंटरफ़ेस भाषा और सीड, यदि हो — ताकि हम वही रिकॉर्ड दोहरा सकें',
    aboutBug5: 'स्क्रीनशॉट (कृपया असली पहचान-पत्र, कार्ड या अन्य संवेदनशील सामग्री न भेजें)',
    qrAlt: 'WeChat आधिकारिक खाते का QR कोड: TinyProductLab'
  };

  C.id = {
    pgBack: '← Kembali ke generator',
    aboutTitleTag: 'Tentang & masukan - TinyProductLab',
    aboutLabH: 'TinyProductLab',
    aboutLabP: 'TinyProductLab membuat alat kecil yang praktis untuk pengembang. Generator alamat dan profil global membantu pengembang, penguji, dan desainer mendapatkan alamat serta profil yang sesuai kebiasaan format tiap negara: membuat begitu dibuka, memperbarui begitu dipilih, mengeluarkan semua kolom langsung, dan tidak perlu akun.',
    aboutCanH: 'Apa yang bisa dilakukan',
    aboutCan1: 'Mencakup seluruh 249 negara / wilayah dalam ISO 3166-1, dengan 22 di antaranya dilokalkan sepenuhnya;',
    aboutCan2: 'Sekali jalan memberikan data orang, alamat dan kontak, kartu pembayaran, pekerjaan, akun dan data teknis, ditambah peta wilayah;',
    aboutCan3: 'Salin per kolom, salin semua, simpan, riwayat lokal, pembuatan massal, dan ekspor CSV/JSON/JSONL/TXT;',
    aboutCan4: 'Seed dapat diulang: seed yang sama dengan filter negara / kota yang sama selalu menghasilkan data yang sama, cocok untuk uji regresi;',
    aboutCan5: 'Antarmuka tersedia dalam 16 bahasa; alamat dan nama lokal selalu keluar dalam bahasa negara yang dipilih.',
    aboutDataH: 'Batas data',
    aboutDataP: 'Negara, pembagian administratif, dan kota berasal dari data nama tempat yang terbuka. Nama, jalan, nomor rumah, telepon, email, perusahaan, dan akun disintesis secara acak dan <b>tidak mewakili orang sungguhan</b>.',
    aboutDataEmail: '<b>Email</b>: memakai bentuk domain penyedia umum dengan bagian lokal acak; keberadaannya tidak pernah diperiksa dan tidak ada surat yang dikirim.',
    aboutDataCard: '<b>Kartu pembayaran</b>: hanya struktur penomoran yang dipublikasikan jaringan kartu yang ditirukan. Tidak memakai basis data BIN sungguhan, dan setiap nomor sengaja gagal pemeriksaan Luhn, jadi tidak satu pun bisa dipakai untuk transaksi nyata.',
    aboutDataHome: '<b>Halaman pribadi</b>: selalu mengarah ke jalur <code>/u/</code> di situs ini, supaya tidak pernah salah mengarahkan ke situs pihak ketiga yang nyata (<a href="u/">penjelasan</a>).',
    aboutDataNo: '<b>Tidak pernah dibuat</b>: nomor KTP atau identitas nasional, nomor paspor, nomor jaminan sosial / SSN, NPWP, rekening bank, IBAN, routing number, atau data biometrik.',
    aboutDataMore: 'Rinciannya ada di <a href="privacy.html">kebijakan privasi</a>, <a href="terms.html">ketentuan penggunaan</a>, dan <a href="sources.html">sumber data</a>.',
    aboutBugH: 'Format yang disarankan untuk melaporkan bug',
    aboutBug1: 'Negara / kota — misalnya Jepang · Tokyo',
    aboutBug2: 'Kolom yang salah — misalnya format kode pos',
    aboutBug3: 'Format yang diharapkan — misalnya 〒XXX-XXXX',
    aboutBug4: 'Bahasa antarmuka dan seed bila ada — agar kami bisa mengulang data yang sama',
    aboutBug5: 'Tangkapan layar (mohon jangan kirim KTP, kartu, atau materi sensitif yang sungguhan)',
    qrAlt: 'Kode QR akun resmi WeChat: TinyProductLab'
  };

  C.th = {
    pgBack: '← กลับไปที่ตัวสร้าง',
    aboutTitleTag: 'เกี่ยวกับและข้อเสนอแนะ - TinyProductLab',
    aboutLabH: 'TinyProductLab',
    aboutLabP: 'TinyProductLab สร้างเครื่องมือเล็ก ๆ ที่ใช้ได้จริงสำหรับนักพัฒนา ตัวสร้างที่อยู่และโปรไฟล์ทั่วโลกช่วยให้นักพัฒนา ผู้ทดสอบ และนักออกแบบได้ที่อยู่และข้อมูลบุคคลที่ตรงกับธรรมเนียมรูปแบบของแต่ละประเทศอย่างรวดเร็ว เปิดแล้วสร้างทันที เลือกแล้วอัปเดตทันที ให้ทุกช่องออกมาตรง ๆ และไม่ต้องสมัครบัญชี',
    aboutCanH: 'ทำอะไรได้',
    aboutCan1: 'ครอบคลุมทั้ง 249 ประเทศ / เขตแดนตาม ISO 3166-1 โดย 22 แห่งแปลครบทั้งหมด',
    aboutCan2: 'ให้ข้อมูลบุคคล ที่อยู่และการติดต่อ บัตรชำระเงิน งาน บัญชีและข้อมูลทางเทคนิคในครั้งเดียว พร้อมแผนที่ของพื้นที่',
    aboutCan3: 'คัดลอกทีละช่อง คัดลอกทั้งหมด บันทึก ประวัติในเครื่อง สร้างเป็นชุด และส่งออก CSV/JSON/JSONL/TXT',
    aboutCan4: 'ทำซ้ำได้ด้วย seed: seed เดิมกับตัวกรองประเทศ / เมืองเดิมจะให้ข้อมูลชุดเดิมทุกครั้ง เหมาะกับการทดสอบถดถอย',
    aboutCan5: 'หน้าจอมี 16 ภาษา ส่วนที่อยู่และชื่อท้องถิ่นจะออกเป็นภาษาของประเทศที่เลือกเสมอ',
    aboutDataH: 'ขอบเขตของข้อมูล',
    aboutDataP: 'ประเทศ เขตการปกครอง และเมือง มาจากข้อมูลชื่อสถานที่แบบเปิด ส่วนชื่อ ถนน บ้านเลขที่ โทรศัพท์ อีเมล บริษัท และบัญชี ถูกสังเคราะห์แบบสุ่มและ<b>ไม่ได้แทนบุคคลจริง</b>',
    aboutDataEmail: '<b>อีเมล</b>: ใช้รูปแบบโดเมนของผู้ให้บริการทั่วไป โดยส่วนหน้าเป็นแบบสุ่ม ไม่มีการตรวจว่ามีอยู่จริงและไม่มีการส่งเมล',
    aboutDataCard: '<b>บัตรชำระเงิน</b>: ทำเลียนแบบเพียงโครงสร้างเลขที่เครือข่ายบัตรเผยแพร่ ไม่ได้ใช้ฐานข้อมูล BIN จริง และทุกหมายเลขตั้งใจให้ไม่ผ่านการตรวจ Luhn จึงใช้ทำธุรกรรมจริงไม่ได้เลย',
    aboutDataHome: '<b>โฮมเพจส่วนตัว</b>: ชี้ไปที่พาธ <code>/u/</code> ของเว็บนี้เสมอ เพื่อไม่ให้พาไปยังเว็บของบุคคลที่สามจริงโดยผิดพลาด (<a href="u/">คำอธิบาย</a>)',
    aboutDataNo: '<b>ไม่สร้างเลย</b>: เลขบัตรประชาชน เลขหนังสือเดินทาง เลขประกันสังคม / SSN เลขผู้เสียภาษี บัญชีธนาคาร IBAN routing number หรือข้อมูลชีวมิติ',
    aboutDataMore: 'รายละเอียดดูที่<a href="privacy.html">นโยบายความเป็นส่วนตัว</a> <a href="terms.html">ข้อกำหนดการใช้งาน</a> และ<a href="sources.html">แหล่งข้อมูล</a>',
    aboutBugH: 'รูปแบบที่แนะนำสำหรับแจ้งข้อผิดพลาด',
    aboutBug1: 'ประเทศ / เมือง — เช่น ญี่ปุ่น · โตเกียว',
    aboutBug2: 'ช่องที่ผิด — เช่น รูปแบบรหัสไปรษณีย์',
    aboutBug3: 'รูปแบบที่ควรเป็น — เช่น 〒XXX-XXXX',
    aboutBug4: 'ภาษาหน้าจอและ seed ถ้ามี — เพื่อให้เราสร้างข้อมูลชุดเดิมซ้ำได้',
    aboutBug5: 'ภาพหน้าจอ (กรุณาอย่าส่งบัตรประชาชน บัตรธนาคาร หรือข้อมูลอ่อนไหวจริง)',
    qrAlt: 'คิวอาร์โค้ดบัญชีทางการ WeChat: TinyProductLab'
  };

  C.vi = {
    pgBack: '← Trở lại trình tạo',
    aboutTitleTag: 'Giới thiệu & góp ý - TinyProductLab',
    aboutLabH: 'TinyProductLab',
    aboutLabP: 'TinyProductLab làm những công cụ nhỏ mà hữu dụng cho người phát triển. Trình tạo địa chỉ và hồ sơ toàn cầu giúp lập trình viên, người kiểm thử và nhà thiết kế nhanh chóng có được địa chỉ cùng hồ sơ đúng quy ước định dạng của từng nước: mở là tạo, chọn là cập nhật, xuất thẳng mọi trường và không cần tài khoản.',
    aboutCanH: 'Làm được gì',
    aboutCan1: 'Bao gồm toàn bộ 249 quốc gia / vùng lãnh thổ theo ISO 3166-1, trong đó 22 nơi được bản địa hóa đầy đủ;',
    aboutCan2: 'Một lần cho ra thông tin người, địa chỉ và liên hệ, thẻ thanh toán, công việc, tài khoản và dữ liệu kỹ thuật, kèm bản đồ khu vực;',
    aboutCan3: 'Sao chép từng trường, sao chép tất cả, lưu, lịch sử cục bộ, tạo theo lô và xuất CSV/JSON/JSONL/TXT;',
    aboutCan4: 'Seed tái lập được: cùng một seed với cùng bộ lọc quốc gia / thành phố luôn cho ra cùng một bản ghi, phù hợp cho kiểm thử hồi quy;',
    aboutCan5: 'Giao diện có 16 ngôn ngữ; địa chỉ và tên bản địa luôn xuất theo ngôn ngữ của nước bạn chọn.',
    aboutDataH: 'Giới hạn dữ liệu',
    aboutDataP: 'Quốc gia, đơn vị hành chính và thành phố lấy từ dữ liệu địa danh công khai. Tên, đường, số nhà, điện thoại, email, công ty và tài khoản được tổng hợp ngẫu nhiên và <b>không đại diện cho người thật</b>.',
    aboutDataEmail: '<b>Email</b>: dùng dạng tên miền của các nhà cung cấp phổ biến với phần cục bộ ngẫu nhiên; không hề kiểm tra sự tồn tại và không gửi thư nào.',
    aboutDataCard: '<b>Thẻ thanh toán</b>: chỉ mô phỏng cấu trúc số mà các tổ chức thẻ công bố. Không dùng cơ sở dữ liệu BIN thật, và mọi số đều cố ý không vượt qua kiểm tra Luhn nên không số nào dùng được cho giao dịch thật.',
    aboutDataHome: '<b>Trang cá nhân</b>: luôn trỏ tới đường dẫn <code>/u/</code> của trang này, để không bao giờ vô tình dẫn tới một website bên thứ ba thật (<a href="u/">giải thích</a>).',
    aboutDataNo: '<b>Không bao giờ tạo</b>: số CMND/CCCD, số hộ chiếu, số an sinh xã hội / SSN, mã số thuế, tài khoản ngân hàng, IBAN, routing number hay dữ liệu sinh trắc.',
    aboutDataMore: 'Chi tiết xem <a href="privacy.html">chính sách quyền riêng tư</a>, <a href="terms.html">điều khoản sử dụng</a> và <a href="sources.html">nguồn dữ liệu</a>.',
    aboutBugH: 'Định dạng gợi ý khi báo lỗi',
    aboutBug1: 'Quốc gia / thành phố — ví dụ Nhật Bản · Tokyo',
    aboutBug2: 'Trường bị sai — ví dụ định dạng mã bưu chính',
    aboutBug3: 'Định dạng mong đợi — ví dụ 〒XXX-XXXX',
    aboutBug4: 'Ngôn ngữ giao diện và seed nếu có — để chúng tôi tái lập đúng bản ghi đó',
    aboutBug5: 'Ảnh chụp màn hình (xin đừng gửi giấy tờ, thẻ hay tài liệu nhạy cảm thật)',
    qrAlt: 'Mã QR tài khoản chính thức WeChat: TinyProductLab'
  };

  root.ADDRGEN_PAGE_COPY = C;
})(typeof globalThis !== 'undefined' ? globalThis : window);
