#!/usr/bin/env node
/*
 * 每月从 Philippine Statistics Authority 的 PSGC API 同步本项目使用的
 * 菲律宾城市与 Barangay 名称。它不会获取街道、门牌或任何个人地址。
 *
 * 需要环境变量：PSGC_API_TOKEN（保存为 GitHub Actions secret）。
 * 使用：node scripts/sync-ph-psgc.mjs
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const token = process.env.PSGC_API_TOKEN;
if (!token) {
  console.log('PSGC_API_TOKEN is not configured; skipping Philippines sync.');
  process.exit(0);
}

const BASE = 'https://classification.psa.gov.ph/psgc/Q2_2026';
const targets = {
  Makati: { aliases: ['Makati'], postal: '1200' },
  'Quezon City': { aliases: ['Quezon City'], postal: '1100' },
  Taguig: { aliases: ['Taguig'], postal: '1630' },
  'Cebu City': { aliases: ['Cebu City'], postal: '6000' },
  'Mandaue City': { aliases: ['Mandaue City', 'City of Mandaue'], postal: '6014' },
  'Davao City': { aliases: ['Davao City', 'City of Davao'], postal: '8000' }
};

function normal(value) {
  return String(value || '').trim().toLocaleLowerCase('en-US').replace(/^city of\s+/, '');
}
function rows(payload) {
  if (Array.isArray(payload)) return payload;
  for (const key of ['results', 'data', 'psgc_data']) {
    if (Array.isArray(payload?.[key])) return payload[key];
  }
  return [];
}
async function request(path, params = {}) {
  const url = new URL(`${BASE}/${path}`);
  url.searchParams.set('token', token);
  Object.entries(params).forEach(([key, value]) => url.searchParams.set(key, String(value)));
  const response = await fetch(url, { headers: { accept: 'application/json' } });
  if (!response.ok) throw new Error(`PSGC ${path}: HTTP ${response.status}`);
  return response.json();
}
async function all(path, params = {}) {
  const first = await request(path, { ...params, page: 1, page_size: 500 });
  const out = rows(first);
  // PSA 的版本有的直接返回完整数组，有的使用分页。两种格式都兼容。
  if (!first?.next && !first?.next_page && out.length < 500) return out;
  for (let page = 2; page <= 200; page += 1) {
    const payload = await request(path, { ...params, page, page_size: 500 });
    const batch = rows(payload);
    out.push(...batch);
    if (!batch.length || batch.length < 500 || (!payload?.next && !payload?.next_page)) break;
  }
  return out;
}

const municipalities = await all('municipalities');
const cities = {};
for (const [name, rule] of Object.entries(targets)) {
  const aliases = new Set(rule.aliases.map(normal));
  const city = municipalities.find((item) => aliases.has(normal(item.area_name)));
  if (!city) throw new Error(`Target city not found in PSGC: ${name}`);
  const municipalityCode = city.mun || city.correspondence_code || city.psgc_code;
  const barangays = await all('barangays', { mun: municipalityCode });
  const names = [...new Set(barangays.map((item) => String(item.area_name || '').trim()).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'en'));
  if (!names.length) throw new Error(`No barangays returned for ${name}`);
  cities[name] = { postal: rule.postal, barangays: names };
}

const payload = {
  source: 'PSA PSGC + PHLPost',
  version: 'PSGC Q2 2026',
  updatedAt: new Date().toISOString().slice(0, 10),
  cities
};
const output = `/* Generated by scripts/sync-ph-psgc.mjs. Do not hand-edit. */\nglobalThis.ADDRGEN_PH_OFFICIAL = Object.freeze(${JSON.stringify(payload, null, 2)});\n`;
writeFileSync(resolve('data/ph-official.js'), output);
console.log(`Updated ${Object.keys(cities).length} Philippine cities from PSA PSGC.`);
